title: The Tab Enumerator
description: A Chromium extension for numbering tabs
logo: https://raw.githubusercontent.com/lxsavage/The-Tab-Enumerator/main/Tab%20Enumerator%20Extension/Resources/images/icon-128.png
theme: jekyll-theme-minimal
